"""
Complete 195 ISO Country Data Model for True Detective.
"""

COUNTRIES = [
    {"name": "Afghanistan", "iso2": "AF", "iso3": "AFG", "region": "Asia", "rss": ["https://news.google.com/rss?hl=en-AF&gl=AF&ceid=AF:en"]},
    {"name": "Albania", "iso2": "AL", "iso3": "ALB", "region": "Europe", "rss": ["https://news.google.com/rss?hl=sq&gl=AL&ceid=AL:sq"]},
    {"name": "Algeria", "iso2": "DZ", "iso3": "DZA", "region": "Africa", "rss": ["https://news.google.com/rss?hl=ar&gl=DZ&ceid=DZ:ar"]},
    {"name": "Andorra", "iso2": "AD", "iso3": "AND", "region": "Europe", "rss": []},
    {"name": "Angola", "iso2": "AO", "iso3": "AGO", "region": "Africa", "rss": []},
    {"name": "Antigua and Barbuda", "iso2": "AG", "iso3": "ATG", "region": "Americas", "rss": []},
    {"name": "Argentina", "iso2": "AR", "iso3": "ARG", "region": "Americas", "rss": ["https://news.google.com/rss?hl=es-419&gl=AR&ceid=AR:es-419"]},
    {"name": "Armenia", "iso2": "AM", "iso3": "ARM", "region": "Asia", "rss": []},
    {"name": "Australia", "iso2": "AU", "iso3": "AUS", "region": "Oceania", "rss": ["https://news.google.com/rss?hl=en-AU&gl=AU&ceid=AU:en"]},
    {"name": "Austria", "iso2": "AT", "iso3": "AUT", "region": "Europe", "rss": ["https://news.google.com/rss?hl=de-AT&gl=AT&ceid=AT:de"]},
    {"name": "Azerbaijan", "iso2": "AZ", "iso3": "AZE", "region": "Asia", "rss": []},
    {"name": "Bahamas", "iso2": "BS", "iso3": "BHS", "region": "Americas", "rss": []},
    {"name": "Bahrain", "iso2": "BH", "iso3": "BHR", "region": "Asia", "rss": []},
    {"name": "Bangladesh", "iso2": "BD", "iso3": "BGD", "region": "Asia", "rss": ["https://news.google.com/rss?hl=bn&gl=BD&ceid=BD:bn"]},
    {"name": "Barbados", "iso2": "BB", "iso3": "BRB", "region": "Americas", "rss": []},
    {"name": "Belarus", "iso2": "BY", "iso3": "BLR", "region": "Europe", "rss": []},
    {"name": "Belgium", "iso2": "BE", "iso3": "BEL", "region": "Europe", "rss": ["https://news.google.com/rss?hl=nl-BE&gl=BE&ceid=BE:nl"]},
    {"name": "Belize", "iso2": "BZ", "iso3": "BLZ", "region": "Americas", "rss": []},
    {"name": "Benin", "iso2": "BJ", "iso3": "BEN", "region": "Africa", "rss": []},
    {"name": "Bhutan", "iso2": "BT", "iso3": "BTN", "region": "Asia", "rss": []},
    {"name": "Bolivia", "iso2": "BO", "iso3": "BOL", "region": "Americas", "rss": []},
    {"name": "Bosnia and Herzegovina", "iso2": "BA", "iso3": "BIH", "region": "Europe", "rss": []},
    {"name": "Botswana", "iso2": "BW", "iso3": "BWA", "region": "Africa", "rss": []},
    {"name": "Brazil", "iso2": "BR", "iso3": "BRA", "region": "Americas", "rss": ["https://news.google.com/rss?hl=pt-BR&gl=BR&ceid=BR:pt-419"]},
    {"name": "Brunei", "iso2": "BN", "iso3": "BRN", "region": "Asia", "rss": []},
    {"name": "Bulgaria", "iso2": "BG", "iso3": "BGR", "region": "Europe", "rss": []},
    {"name": "Burkina Faso", "iso2": "BF", "iso3": "BFA", "region": "Africa", "rss": []},
    {"name": "Burundi", "iso2": "BI", "iso3": "BDI", "region": "Africa", "rss": []},
    {"name": "Cabo Verde", "iso2": "CV", "iso3": "CPV", "region": "Africa", "rss": []},
    {"name": "Cambodia", "iso2": "KH", "iso3": "KHM", "region": "Asia", "rss": []},
    {"name": "Cameroon", "iso2": "CM", "iso3": "CMR", "region": "Africa", "rss": []},
    {"name": "Canada", "iso2": "CA", "iso3": "CAN", "region": "Americas", "rss": ["https://news.google.com/rss?hl=en-CA&gl=CA&ceid=CA:en"]},
    {"name": "Central African Republic", "iso2": "CF", "iso3": "CAF", "region": "Africa", "rss": []},
    {"name": "Chad", "iso2": "TD", "iso3": "TCD", "region": "Africa", "rss": []},
    {"name": "Chile", "iso2": "CL", "iso3": "CHL", "region": "Americas", "rss": []},
    {"name": "China", "iso2": "CN", "iso3": "CHN", "region": "Asia", "rss": ["https://news.google.com/rss?hl=zh-CN&gl=CN&ceid=CN:zh-Hans"]},
    {"name": "Colombia", "iso2": "CO", "iso3": "COL", "region": "Americas", "rss": []},
    {"name": "Comoros", "iso2": "KM", "iso3": "COM", "region": "Africa", "rss": []},
    {"name": "Congo (Congo-Brazzaville)", "iso2": "CG", "iso3": "COG", "region": "Africa", "rss": []},
    {"name": "Costa Rica", "iso2": "CR", "iso3": "CRI", "region": "Americas", "rss": []},
    {"name": "Croatia", "iso2": "HR", "iso3": "HRV", "region": "Europe", "rss": []},
    {"name": "Cuba", "iso2": "CU", "iso3": "CUB", "region": "Americas", "rss": []},
    {"name": "Cyprus", "iso2": "CY", "iso3": "CYP", "region": "Europe", "rss": []},
    {"name": "Czechia (Czech Republic)", "iso2": "CZ", "iso3": "CZE", "region": "Europe", "rss": []},
    {"name": "Democratic Republic of the Congo", "iso2": "CD", "iso3": "COD", "region": "Africa", "rss": []},
    {"name": "Denmark", "iso2": "DK", "iso3": "DNK", "region": "Europe", "rss": []},
    {"name": "Djibouti", "iso2": "DJ", "iso3": "DJI", "region": "Africa", "rss": []},
    {"name": "Dominica", "iso2": "DM", "iso3": "DMA", "region": "Americas", "rss": []},
    {"name": "Dominican Republic", "iso2": "DO", "iso3": "DOM", "region": "Americas", "rss": []},
    {"name": "Ecuador", "iso2": "EC", "iso3": "ECU", "region": "Americas", "rss": []},
    {"name": "Egypt", "iso2": "EG", "iso3": "EGY", "region": "Africa", "rss": ["https://news.google.com/rss?hl=ar&gl=EG&ceid=EG:ar"]},
    {"name": "El Salvador", "iso2": "SV", "iso3": "SLV", "region": "Americas", "rss": []},
    {"name": "Equatorial Guinea", "iso2": "GQ", "iso3": "GNQ", "region": "Africa", "rss": []},
    {"name": "Eritrea", "iso2": "ER", "iso3": "ERI", "region": "Africa", "rss": []},
    {"name": "Estonia", "iso2": "EE", "iso3": "EST", "region": "Europe", "rss": []},
    {"name": "Eswatini", "iso2": "SZ", "iso3": "SWZ", "region": "Africa", "rss": []},
    {"name": "Ethiopia", "iso2": "ET", "iso3": "ETH", "region": "Africa", "rss": []},
    {"name": "Fiji", "iso2": "FJ", "iso3": "FJI", "region": "Oceania", "rss": []},
    {"name": "Finland", "iso2": "FI", "iso3": "FIN", "region": "Europe", "rss": []},
    {"name": "France", "iso2": "FR", "iso3": "FRA", "region": "Europe", "rss": ["https://news.google.com/rss?hl=fr&gl=FR&ceid=FR:fr"]},
    {"name": "Gabon", "iso2": "GA", "iso3": "GAB", "region": "Africa", "rss": []},
    {"name": "Gambia", "iso2": "GM", "iso3": "GMB", "region": "Africa", "rss": []},
    {"name": "Georgia", "iso2": "GE", "iso3": "GEO", "region": "Asia", "rss": []},
    {"name": "Germany", "iso2": "DE", "iso3": "DEU", "region": "Europe", "rss": ["https://news.google.com/rss?hl=de&gl=DE&ceid=DE:de"]},
    {"name": "Ghana", "iso2": "GH", "iso3": "GHA", "region": "Africa", "rss": []},
    {"name": "Greece", "iso2": "GR", "iso3": "GRC", "region": "Europe", "rss": []},
    {"name": "Grenada", "iso2": "GD", "iso3": "GRD", "region": "Americas", "rss": []},
    {"name": "Guatemala", "iso2": "GT", "iso3": "GTM", "region": "Americas", "rss": []},
    {"name": "Guinea", "iso2": "GN", "iso3": "GIN", "region": "Africa", "rss": []},
    {"name": "Guinea-Bissau", "iso2": "GW", "iso3": "GNB", "region": "Africa", "rss": []},
    {"name": "Guyana", "iso2": "GY", "iso3": "GUY", "region": "Americas", "rss": []},
    {"name": "Haiti", "iso2": "HT", "iso3": "HTI", "region": "Americas", "rss": []},
    {"name": "Holy See", "iso2": "VA", "iso3": "VAT", "region": "Europe", "rss": []},
    {"name": "Honduras", "iso2": "HN", "iso3": "HND", "region": "Americas", "rss": []},
    {"name": "Hungary", "iso2": "HU", "iso3": "HUN", "region": "Europe", "rss": []},
    {"name": "Iceland", "iso2": "IS", "iso3": "ISL", "region": "Europe", "rss": []},
    {"name": "India", "iso2": "IN", "iso3": "IND", "region": "Asia", "rss": ["https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en"]},
    {"name": "Indonesia", "iso2": "ID", "iso3": "IDN", "region": "Asia", "rss": ["https://news.google.com/rss?hl=id&gl=ID&ceid=ID:id"]},
    {"name": "Iran", "iso2": "IR", "iso3": "IRN", "region": "Asia", "rss": []},
    {"name": "Iraq", "iso2": "IQ", "iso3": "IRQ", "region": "Asia", "rss": []},
    {"name": "Ireland", "iso2": "IE", "iso3": "IRL", "region": "Europe", "rss": []},
    {"name": "Israel", "iso2": "IL", "iso3": "ISR", "region": "Asia", "rss": ["https://news.google.com/rss?hl=he&gl=IL&ceid=IL:he"]},
    {"name": "Italy", "iso2": "IT", "iso3": "ITA", "region": "Europe", "rss": ["https://news.google.com/rss?hl=it&gl=IT&ceid=IT:it"]},
    {"name": "Jamaica", "iso2": "JM", "iso3": "JAM", "region": "Americas", "rss": []},
    {"name": "Japan", "iso2": "JP", "iso3": "JPN", "region": "Asia", "rss": ["https://news.google.com/rss?hl=ja&gl=JP&ceid=JP:ja"]},
    {"name": "Jordan", "iso2": "JO", "iso3": "JOR", "region": "Asia", "rss": []},
    {"name": "Kazakhstan", "iso2": "KZ", "iso3": "KAZ", "region": "Asia", "rss": []},
    {"name": "Kenya", "iso2": "KE", "iso3": "KEN", "region": "Africa", "rss": ["https://news.google.com/rss?hl=en-KE&gl=KE&ceid=KE:en"]},
    {"name": "Kiribati", "iso2": "KI", "iso3": "KIR", "region": "Oceania", "rss": []},
    {"name": "Kuwait", "iso2": "KW", "iso3": "KWT", "region": "Asia", "rss": []},
    {"name": "Kyrgyzstan", "iso2": "KG", "iso3": "KGZ", "region": "Asia", "rss": []},
    {"name": "Laos", "iso2": "LA", "iso3": "LAO", "region": "Asia", "rss": []},
    {"name": "Latvia", "iso2": "LV", "iso3": "LVA", "region": "Europe", "rss": []},
    {"name": "Lebanon", "iso2": "LB", "iso3": "LBN", "region": "Asia", "rss": []},
    {"name": "Lesotho", "iso2": "LS", "iso3": "LSO", "region": "Africa", "rss": []},
    {"name": "Liberia", "iso2": "LR", "iso3": "LBR", "region": "Africa", "rss": []},
    {"name": "Libya", "iso2": "LY", "iso3": "LBY", "region": "Africa", "rss": []},
    {"name": "Liechtenstein", "iso2": "LI", "iso3": "LIE", "region": "Europe", "rss": []},
    {"name": "Lithuania", "iso2": "LT", "iso3": "LTU", "region": "Europe", "rss": []},
    {"name": "Luxembourg", "iso2": "LU", "iso3": "LUX", "region": "Europe", "rss": []},
    {"name": "Madagascar", "iso2": "MG", "iso3": "MDG", "region": "Africa", "rss": []},
    {"name": "Malawi", "iso2": "MW", "iso3": "MWI", "region": "Africa", "rss": []},
    {"name": "Malaysia", "iso2": "MY", "iso3": "MYS", "region": "Asia", "rss": ["https://news.google.com/rss?hl=ms&gl=MY&ceid=MY:ms"]},
    {"name": "Maldives", "iso2": "MV", "iso3": "MDV", "region": "Asia", "rss": []},
    {"name": "Mali", "iso2": "ML", "iso3": "MLI", "region": "Africa", "rss": []},
    {"name": "Malta", "iso2": "MT", "iso3": "MLT", "region": "Europe", "rss": []},
    {"name": "Marshall Islands", "iso2": "MH", "iso3": "MHL", "region": "Oceania", "rss": []},
    {"name": "Mauritania", "iso2": "MR", "iso3": "MRT", "region": "Africa", "rss": []},
    {"name": "Mauritius", "iso2": "MU", "iso3": "MUS", "region": "Africa", "rss": []},
    {"name": "Mexico", "iso2": "MX", "iso3": "MEX", "region": "Americas", "rss": ["https://news.google.com/rss?hl=es-419&gl=MX&ceid=MX:es-419"]},
    {"name": "Micronesia", "iso2": "FM", "iso3": "FSM", "region": "Oceania", "rss": []},
    {"name": "Moldova", "iso2": "MD", "iso3": "MDA", "region": "Europe", "rss": []},
    {"name": "Monaco", "iso2": "MC", "iso3": "MCO", "region": "Europe", "rss": []},
    {"name": "Mongolia", "iso2": "MN", "iso3": "MNG", "region": "Asia", "rss": []},
    {"name": "Montenegro", "iso2": "ME", "iso3": "MNE", "region": "Europe", "rss": []},
    {"name": "Morocco", "iso2": "MA", "iso3": "MAR", "region": "Africa", "rss": []},
    {"name": "Mozambique", "iso2": "MZ", "iso3": "MOZ", "region": "Africa", "rss": []},
    {"name": "Myanmar", "iso2": "MM", "iso3": "MMR", "region": "Asia", "rss": []},
    {"name": "Namibia", "iso2": "NA", "iso3": "NAM", "region": "Africa", "rss": []},
    {"name": "Nauru", "iso2": "NR", "iso3": "NRU", "region": "Oceania", "rss": []},
    {"name": "Nepal", "iso2": "NP", "iso3": "NPL", "region": "Asia", "rss": []},
    {"name": "Netherlands", "iso2": "NL", "iso3": "NLD", "region": "Europe", "rss": ["https://news.google.com/rss?hl=nl&gl=NL&ceid=NL:nl"]},
    {"name": "New Zealand", "iso2": "NZ", "iso3": "NZL", "region": "Oceania", "rss": ["https://news.google.com/rss?hl=en-NZ&gl=NZ&ceid=NZ:en"]},
    {"name": "Nicaragua", "iso2": "NI", "iso3": "NIC", "region": "Americas", "rss": []},
    {"name": "Niger", "iso2": "NE", "iso3": "NER", "region": "Africa", "rss": []},
    {"name": "Nigeria", "iso2": "NG", "iso3": "NGA", "region": "Africa", "rss": ["https://news.google.com/rss?hl=en-NG&gl=NG&ceid=NG:en"]},
    {"name": "North Korea", "iso2": "KP", "iso3": "PRK", "region": "Asia", "rss": []},
    {"name": "North Macedonia", "iso2": "MK", "iso3": "MKD", "region": "Europe", "rss": []},
    {"name": "Norway", "iso2": "NO", "iso3": "NOR", "region": "Europe", "rss": []},
    {"name": "Oman", "iso2": "OM", "iso3": "OMN", "region": "Asia", "rss": []},
    {"name": "Pakistan", "iso2": "PK", "iso3": "PAK", "region": "Asia", "rss": ["https://news.google.com/rss?hl=en-PK&gl=PK&ceid=PK:en"]},
    {"name": "Palau", "iso2": "PW", "iso3": "PLW", "region": "Oceania", "rss": []},
    {"name": "Palestine", "iso2": "PS", "iso3": "PSE", "region": "Asia", "rss": []},
    {"name": "Panama", "iso2": "PA", "iso3": "PAN", "region": "Americas", "rss": []},
    {"name": "Papua New Guinea", "iso2": "PG", "iso3": "PNG", "region": "Oceania", "rss": []},
    {"name": "Paraguay", "iso2": "PY", "iso3": "PRY", "region": "Americas", "rss": []},
    {"name": "Peru", "iso2": "PE", "iso3": "PER", "region": "Americas", "rss": []},
    {"name": "Philippines", "iso2": "PH", "iso3": "PHL", "region": "Asia", "rss": ["https://news.google.com/rss?hl=en-PH&gl=PH&ceid=PH:en"]},
    {"name": "Poland", "iso2": "PL", "iso3": "POL", "region": "Europe", "rss": ["https://news.google.com/rss?hl=pl&gl=PL&ceid=PL:pl"]},
    {"name": "Portugal", "iso2": "PT", "iso3": "PRT", "region": "Europe", "rss": []},
    {"name": "Qatar", "iso2": "QA", "iso3": "QAT", "region": "Asia", "rss": []},
    {"name": "Romania", "iso2": "RO", "iso3": "ROU", "region": "Europe", "rss": []},
    {"name": "Russia", "iso2": "RU", "iso3": "RUS", "region": "Europe", "rss": ["https://news.google.com/rss?hl=ru&gl=RU&ceid=RU:ru"]},
    {"name": "Rwanda", "iso2": "RW", "iso3": "RWA", "region": "Africa", "rss": []},
    {"name": "Saint Kitts and Nevis", "iso2": "KN", "iso3": "KNA", "region": "Americas", "rss": []},
    {"name": "Saint Lucia", "iso2": "LC", "iso3": "LCA", "region": "Americas", "rss": []},
    {"name": "Saint Vincent and the Grenadines", "iso2": "VC", "iso3": "VCT", "region": "Americas", "rss": []},
    {"name": "Samoa", "iso2": "WS", "iso3": "WSM", "region": "Oceania", "rss": []},
    {"name": "San Marino", "iso2": "SM", "iso3": "SMR", "region": "Europe", "rss": []},
    {"name": "Sao Tome and Principe", "iso2": "ST", "iso3": "STP", "region": "Africa", "rss": []},
    {"name": "Saudi Arabia", "iso2": "SA", "iso3": "SAU", "region": "Asia", "rss": ["https://news.google.com/rss?hl=ar&gl=SA&ceid=SA:ar"]},
    {"name": "Senegal", "iso2": "SN", "iso3": "SEN", "region": "Africa", "rss": []},
    {"name": "Serbia", "iso2": "RS", "iso3": "SRB", "region": "Europe", "rss": []},
    {"name": "Seychelles", "iso2": "SC", "iso3": "SYC", "region": "Africa", "rss": []},
    {"name": "Sierra Leone", "iso2": "SL", "iso3": "SLE", "region": "Africa", "rss": []},
    {"name": "Singapore", "iso2": "SG", "iso3": "SGP", "region": "Asia", "rss": ["https://news.google.com/rss?hl=en-SG&gl=SG&ceid=SG:en"]},
    {"name": "Slovakia", "iso2": "SK", "iso3": "SVK", "region": "Europe", "rss": []},
    {"name": "Slovenia", "iso2": "SI", "iso3": "SVN", "region": "Europe", "rss": []},
    {"name": "Solomon Islands", "iso2": "SB", "iso3": "SLB", "region": "Oceania", "rss": []},
    {"name": "Somalia", "iso2": "SO", "iso3": "SOM", "region": "Africa", "rss": []},
    {"name": "South Africa", "iso2": "ZA", "iso3": "ZAF", "region": "Africa", "rss": ["https://news.google.com/rss?hl=en-ZA&gl=ZA&ceid=ZA:en"]},
    {"name": "South Korea", "iso2": "KR", "iso3": "KOR", "region": "Asia", "rss": ["https://news.google.com/rss?hl=ko&gl=KR&ceid=KR:ko"]},
    {"name": "South Sudan", "iso2": "SS", "iso3": "SSD", "region": "Africa", "rss": []},
    {"name": "Spain", "iso2": "ES", "iso3": "ESP", "region": "Europe", "rss": ["https://news.google.com/rss?hl=es&gl=ES&ceid=ES:es"]},
    {"name": "Sri Lanka", "iso2": "LK", "iso3": "LKA", "region": "Asia", "rss": []},
    {"name": "Sudan", "iso2": "SD", "iso3": "SDN", "region": "Africa", "rss": []},
    {"name": "Suriname", "iso2": "SR", "iso3": "SUR", "region": "Americas", "rss": []},
    {"name": "Sweden", "iso2": "SE", "iso3": "SWE", "region": "Europe", "rss": []},
    {"name": "Switzerland", "iso2": "CH", "iso3": "CHE", "region": "Europe", "rss": []},
    {"name": "Syria", "iso2": "SY", "iso3": "SYR", "region": "Asia", "rss": []},
    {"name": "Tajikistan", "iso2": "TJ", "iso3": "TJK", "region": "Asia", "rss": []},
    {"name": "Tanzania", "iso2": "TZ", "iso3": "TZA", "region": "Africa", "rss": []},
    {"name": "Thailand", "iso2": "TH", "iso3": "THA", "region": "Asia", "rss": ["https://news.google.com/rss?hl=th&gl=TH&ceid=TH:th"]},
    {"name": "Timor-Leste", "iso2": "TL", "iso3": "TLS", "region": "Asia", "rss": []},
    {"name": "Togo", "iso2": "TG", "iso3": "TGO", "region": "Africa", "rss": []},
    {"name": "Tonga", "iso2": "TO", "iso3": "TON", "region": "Oceania", "rss": []},
    {"name": "Trinidad and Tobago", "iso2": "TT", "iso3": "TTO", "region": "Americas", "rss": []},
    {"name": "Tunisia", "iso2": "TN", "iso3": "TUN", "region": "Africa", "rss": []},
    {"name": "Turkey", "iso2": "TR", "iso3": "TUR", "region": "Asia", "rss": ["https://news.google.com/rss?hl=tr&gl=TR&ceid=TR:tr"]},
    {"name": "Turkmenistan", "iso2": "TM", "iso3": "TKM", "region": "Asia", "rss": []},
    {"name": "Tuvalu", "iso2": "TV", "iso3": "TUV", "region": "Oceania", "rss": []},
    {"name": "Uganda", "iso2": "UG", "iso3": "UGA", "region": "Africa", "rss": []},
    {"name": "Ukraine", "iso2": "UA", "iso3": "UKR", "region": "Europe", "rss": []},
    {"name": "United Arab Emirates", "iso2": "AE", "iso3": "ARE", "region": "Asia", "rss": ["https://news.google.com/rss?hl=ar&gl=AE&ceid=AE:ar"]},
    {"name": "United Kingdom", "iso2": "GB", "iso3": "GBR", "region": "Europe", "rss": ["https://news.google.com/rss?hl=en-GB&gl=GB&ceid=GB:en"]},
    {"name": "United States", "iso2": "US", "iso3": "USA", "region": "Americas", "rss": ["https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en"]},
    {"name": "Uruguay", "iso2": "UY", "iso3": "URY", "region": "Americas", "rss": []},
    {"name": "Uzbekistan", "iso2": "UZ", "iso3": "UZB", "region": "Asia", "rss": []},
    {"name": "Vanuatu", "iso2": "VU", "iso3": "VUT", "region": "Oceania", "rss": []},
    {"name": "Venezuela", "iso2": "VE", "iso3": "VEN", "region": "Americas", "rss": []},
    {"name": "Vietnam", "iso2": "VN", "iso3": "VNM", "region": "Asia", "rss": ["https://news.google.com/rss?hl=vi&gl=VN&ceid=VN:vi"]},
    {"name": "Yemen", "iso2": "YE", "iso3": "YEM", "region": "Asia", "rss": []},
    {"name": "Zambia", "iso2": "ZM", "iso3": "ZMB", "region": "Africa", "rss": []},
    {"name": "Zimbabwe", "iso2": "ZW", "iso3": "ZWE", "region": "Africa", "rss": []}
]

# Ensure every single country has at least one working RSS feed endpoint
import urllib.parse
for country in COUNTRIES:
    if not country["rss"]:
        encoded_name = urllib.parse.quote(country["name"])
        country["rss"] = [f"https://news.google.com/rss/search?q={encoded_name}&hl=en-US&gl=US&ceid=US:en"]

def get_country_by_name(name):
    for c in COUNTRIES:
        if c["name"].lower() == name.lower():
            return c
    return None